@chcp 65001
SET GITSYNC_V8VERSION=8.3.18
SET GITSYNC_VERBOSE=Ложь
set GITSYNC_STORAGE_USER=ci-bot
set GITSYNC_STORAGE_PASSWORD=Secret
set GITSYNC_WORKDIR=./src/
set GITSYNC_STORAGE_PATH=tcp://127.0.0.1

call gitsync init 